day10/day10/day10/urls.py
from django.contrib import admin
from django.urls import path
from web.views import account, admin, phone

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('login/', account.login),
    path('logout/', account.logout),
    path('img/code/', account.img_code),
    path('home/', account.home),
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/edit/<int:aid>/', admin.admin_edit),
    path('admin/delete/', admin.admin_delete),
    path('phone/list/', phone.phone_list),
    path('phone/add/', phone.phone_add),
    path('phone/edit/<int:aid>/', phone.phone_edit),
    path('phone/delete/', phone.phone_delete),
]

day10/day10/web/models.py
from django.db import models

class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name="标题", max_length=16)

    def __str__(self):
        return self.title

class Admin(models.Model):
    """管理员表"""
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄", null=True, blank=True)
    gender = models.IntegerField(verbose_name="性别", choices=[(1,"男"),(2,"女")], default=1)

    depart = models.ForeignKey(verbose_name="部门", to="Department", on_delete=models.CASCADE)

class Phone(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    price = models.PositiveIntegerField(verbose_name="价格",default=0)
    level = models.SmallIntegerField(
        verbose_name="级别",
        choices=[
            (1, "1级"),
            (2, "2级"),
            (3, "3级"),
            (4, "4级"),
        ],
        default=1
    )
    status_choices = (
        (1, "已使用"),
        (2, "未使用"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)
    admin = models.ForeignKey(verbose_name="管理员", to="Admin", on_delete=models.CASCADE)

day10/day10/web/views/phone.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django import forms
from web import models
from utils.encrypt import md5

def phone_list(request):
    """用户列表"""
    queryset = models.Phone.objects.all().order_by("-id")
    # for row in queryset:
    #     print(row.username, row.password, row.gender, row.get_gender_display(), row.depart.title)

    return render(request, 'phone_list.html', {"queryset": queryset})

class PhoneModelForm(forms.ModelForm):
    class Meta:
        model = models.Phone
        fields = ['mobile', 'price','level','status', 'admin']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    # 自定义操作，找到所有的字段
    #     print(self.fields)
        for name, field_object in self.fields.items():
            # print(name, field_object)
            field_object.widget.attrs = {"class": "form-control"}

def phone_add(request):
    if request.method == "GET":
        form = PhoneModelForm()
        return render(request, 'phone_form.html', {'form':form})

    form = PhoneModelForm(data=request.POST)
    if not form.is_valid():
        return render(request, 'phone_form.html', {'form': form})

    form.save()
    return redirect('/phone/list/')

class PhoneEditModelForm(forms.ModelForm):
    class Meta:
        model = models.Phone
        fields = ['mobile', 'price','level','status', 'admin']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    # 自定义操作，找到所有的字段
    #     print(self.fields)
        for name, field_object in self.fields.items():
            # print(name, field_object)
            field_object.widget.attrs = {"class": "form-control"}

def phone_edit(request, aid):
    phone_object = models.Phone.objects.filter(id=aid).first()

    if request.method == "GET":
        form = PhoneEditModelForm(instance=phone_object)
        return render(request, 'phone_form.html', {'form': form})

    form = PhoneEditModelForm(instance=phone_object, data=request.POST)
    if not form.is_valid():
        return render(request, 'phone_form.html', {"form": form})

    form.save()

    return redirect('/phone/list/')

def phone_delete(request):
    aid = request.GET.get("aid")

    models.Phone.objects.filter(id=aid).delete()

    # return JsonResponse({"status": False, 'error': 'ID不能为空'})
    return JsonResponse({"status": True})

day10/day10/web/templates/admin_form.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">
      <div class="panel-heading"><span class="glyphicon glyphicon-indent-right" aria-hidden="true"></span>  表单操作</div>
      <div class="panel-body">
          <form class="form-horizontal" method="post" novalidate>
              {% csrf_token %}
               <div class="row">
                  {% for field in form %}
                   <div class="col-xs-6">
                  <div class="form-group" style="margin-bottom: 25px;">
                    <label class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10" style="position: relative">
                      {{ field }}
                        <span style="color: red; position: absolute;">{{ field.errors.0 }}</span>
                    </div>
                  </div>
                       </div>
                  {% endfor %}
              </div>
              <div class="row">
              <div class="form-group">
                  <div class="col-xs-6">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-primary">保 存</button>
                </div>
                      </div>
              </div>
                  </div>
            </form>

      </div>
    </div>


{% endblock %}

day10/day10/web/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
<div style="margin-bottom: 10px">
    <a class="btn btn-success" href="/admin/add/">
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建用户
    </a>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>用户名</th>
        <th>年龄</th>
        <th>性别</th>
        <th>部门</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for row in queryset %}
    <tr>
        <td>{{ row.id }}</td>
        <td>{{ row.username }}</td>
        <td>{{ row.age }}</td>
        <td>{{ row.get_gender_display }}</td>
        <td>{{ row.depart.title }}</td>
        <td>
            <a class="btn btn-primary btn-xs" href="/admin/edit/{{ row.id }}">编辑</a>

            <input type="button" value="删除" class="btn btn-danger btn-xs" onclick="deleteAction({{ row.id }});">
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close"></button>
      <h4>是否确定要删除？</h4>
      <p style="margin: 20px 0;">删除后，与之关联的所有相关的数据都会被删除掉，确认是否继续？</p>
      <p>
        <button type="button" class="btn btn-danger" onclick="confirmDelete()">确 认</button>
        <button type="button" class="btn btn-default" onclick="cancelDelete()">取 消</button>
      </p>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
    <script>
        DELETE_ID = 0;

        function deleteAction(id){
            DELETE_ID = id;
            $('#myModal').modal('show');
        }

        function confirmDelete(){
            $.ajax({
                url: "/admin/delete/",
                type: "GET",
                data: {
                    aid: DELETE_ID
                },
                dataType: "JSON",
                success: function (res) {
                    if(res.status){
                        location.reload()
                    } else {
                        alert(res.error);
                    }
                    console.log("请求返回值:", res);
                }
            })
        };

        function cancelDelete(){
            DELETE_ID = 0;
            $('#myModal').modal('hide');
        }
    </script>

{% endblock %}

day10/day10/web/templates/home.html
{% extends 'layout.html' %}

{% block content %}
  <h3>欢迎{{ request.info_dict.name }}登录靓号系统</h3>
{% endblock %}

day10/day10/web/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default" style="border-radius:0;">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">靓号管理系统</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/admin/list/">用户管理</a></li>
        <li><a href="/phone/list/">号码管理</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.info_dict.name }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">个人资料</a></li>
            <li><a href="#">修改密码</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/logout/">注销</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  {% block content %}{% endblock %}

</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

day10/day10/web/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .login-box{
            width: 400px;

            margin-left:auto;
            margin-right:auto;
            border: 1px solid #dddddd;
            margin-top:220px;
            padding-left:20px;
            padding-right:20px;
            padding-bottom: 20px;
        }
        .login-box h2{
            text-align:center;
        }

    </style>
</head>
<body>
    <div class="login-box">
        <h2>用户登录</h2>
        <form method="post" action="/login/" novalidate>
          {% csrf_token %}
          <div class="form-group">
            <label>{{ form.username.label }}</label>
<!--            <input type="text" class="form-control" placeholder="请输入用户名" name="user">-->
              {{ form.username }}
              <span style="color:red;">{{ form.username.errors.0 }}</span>
          </div>
          <div class="form-group">
            <label>{{ form.password.label }}</label>
<!--            <input type="password" class="form-control" placeholder="请输入密码" name="pwd">-->
              {{ form.password }}
              <span style="color:red;">{{ form.password.errors.0 }}</span>
          </div>
          <div class="form-group">
            <label>验证码</label>
              <div class="row">
                  <div class="col-xs-6">
                      {{ form.code }}
                  </div>
                  <div class="col-xs-6">
                      <img src="/img/code/" id="codeImage">
                  </div>
              </div>
              <span style="color:red;">{{ form.code.errors.0 }}</span>
          </div>

          <button type="submit" class="btn btn-primary">提 交</button>
          <span style="color:red;">{{ error }}</span>
        </form>
    </div>
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script>
            $(function (){
                $("#codeImage").click(function () {
                    var url = $(this).attr('src');
                    $(this).attr('src',url + "?");
                });
            })
        </script>

<!--    <script src="{% static 'bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>-->
</body>
</html>

day10/day10/web/templates/phone_form.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">
      <div class="panel-heading"><span class="glyphicon glyphicon-indent-right" aria-hidden="true"></span>  表单操作</div>
      <div class="panel-body">
          <form class="form-horizontal" method="post" novalidate>
              {% csrf_token %}
               <div class="row">
                  {% for field in form %}
                   <div class="col-xs-6">
                  <div class="form-group" style="margin-bottom: 25px;">
                    <label class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10" style="position: relative">
                      {{ field }}
                        <span style="color: red; position: absolute;">{{ field.errors.0 }}</span>
                    </div>
                  </div>
                       </div>
                  {% endfor %}
              </div>
              <div class="row">
              <div class="form-group">
                  <div class="col-xs-6">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-primary">保 存</button>
                </div>
                      </div>
              </div>
                  </div>
            </form>

      </div>
    </div>


{% endblock %}

day10/day10/web/templates/phone_list.html
{% extends 'layout.html' %}

{% block content %}
<div style="margin-bottom: 10px">
    <a class="btn btn-success" href="/phone/add/">
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建手机号
    </a>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>手机号</th>
        <th>价格</th>
        <th>级别</th>
        <th>状态</th>
        <th>管理员</th>
    </tr>
    </thead>
    <tbody>
    {% for row in queryset %}
    <tr>
        <td>{{ row.id }}</td>
        <td>{{ row.mobile }}</td>
        <td>{{ row.price }}</td>
        <td>{{ row.get_level_display }}</td>
        <td>{{ row.get_status_display }}</td>
        <td>{{ row.admin.username }}</td>
        <td>
            <a class="btn btn-primary btn-xs" href="/phone/edit/{{ row.id }}">编辑</a>

            <input type="button" value="删除" class="btn btn-danger btn-xs" onclick="deleteAction({{ row.id }});">
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close"></button>
      <h4>是否确定要删除？</h4>
      <p style="margin: 20px 0;">删除后，与之关联的所有相关的数据都会被删除掉，确认是否继续？</p>
      <p>
        <button type="button" class="btn btn-danger" onclick="confirmDelete()">确 认</button>
        <button type="button" class="btn btn-default" onclick="cancelDelete()">取 消</button>
      </p>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
    <script>
        DELETE_ID = 0;

        function deleteAction(id){
            DELETE_ID = id;
            $('#myModal').modal('show');
        }

        function confirmDelete(){
            $.ajax({
                url: "/phone/delete/",
                type: "GET",
                data: {
                    aid: DELETE_ID
                },
                dataType: "JSON",
                success: function (res) {
                    if(res.status){
                        location.reload()
                    } else {
                        alert(res.error);
                    }
                    console.log("请求返回值:", res);
                }
            })
        };

        function cancelDelete(){
            DELETE_ID = 0;
            $('#myModal').modal('hide');
        }
    </script>

{% endblock %}